name: material_neumorphic_checkbox
description: |
  A Flutter package for creating Neumorphic checkbox.
version: 1.1.4
repository: https://github.com/gsmlg-dev/material-neumorphic.git

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  material_neumorphic_theme: ^1.1.3
  material_neumorphic_button: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.21.0
