name: material_neumorphic_theme
description: |
  A Flutter package for creating Neumorphic theme.
  Use material colorscheme to set neumorphic theme colors.
version: 1.1.2
repository: https://github.com/gsmlg-dev/material-neumorphic.git

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.21.0
