name: material_neumorphic_text
description: |
  A Flutter package for creating Neumorphic text.
version: 1.1.1
repository: https://github.com/gsmlg-dev/material-neumorphic.git

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  material_neumorphic_theme: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.21.0
