name: material_neumorphic_icon
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/gsmlg-dev/material-neumorphic.git

environment:
  sdk: ^3.0.6

dependencies:
  flutter:
    sdk: flutter
  material_neumorphic_theme: ^1.0.0
  material_neumorphic_text: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.21.0

flutter:
  fonts:
    - family: NeumorphicIcons
      fonts:
        - asset: fonts/NeumorphicIcons.ttf
