name: material_neumorphic_button
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

dependencies:
  flutter:
    sdk: flutter
  material_neumorphic_theme:
    path: "../material_neumorphic_theme"

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.21.0
