name: material_neumorphic_radio
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/gsmlg-dev/material-neumorphic.git

environment:
  sdk: ^3.0.6

dependencies:
  flutter:
    sdk: flutter
  material_neumorphic_theme:
    path: "../material_neumorphic_theme"
  material_neumorphic_button:
    path: "../material_neumorphic_button"

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.21.0
