name: material_neumorphic
description: |
  A Flutter package for creating Neumorphic theme widgets.
  This package includes all neumorphic widgets.
  This package can fit with material colorScheme.
version: 1.0.0
repository: https://github.com/gsmlg-dev/material-neumorphic.git

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  material_neumorphic_app_bar: ^1.0.0
  material_neumorphic_background: ^1.0.0
  material_neumorphic_button: ^1.0.0
  material_neumorphic_checkbox: ^1.0.0
  material_neumorphic_icon: ^1.0.0
  material_neumorphic_indicator: ^1.0.0
  material_neumorphic_progress: ^1.0.0
  material_neumorphic_radio: ^1.0.0
  material_neumorphic_slider: ^1.0.0
  material_neumorphic_switch: ^1.0.0
  material_neumorphic_text: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
