name: material_neumorphic
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/gsmlg-dev/material-neumorphic.git

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  material_neumorphic_app_bar:
    path: ../material_neumorphic_app_bar
  material_neumorphic_background:
    path: ../material_neumorphic_background
  material_neumorphic_button:
    path: ../material_neumorphic_button
  material_neumorphic_checkbox:
    path: ../material_neumorphic_checkbox
  material_neumorphic_icon:
    path: ../material_neumorphic_icon
  material_neumorphic_indicator:
    path: ../material_neumorphic_indicator
  material_neumorphic_progress:
    path: ../material_neumorphic_progress
  material_neumorphic_radio:
    path: ../material_neumorphic_radio
  material_neumorphic_slider:
    path: ../material_neumorphic_slider
  material_neumorphic_switch:
    path: ../material_neumorphic_switch
  material_neumorphic_text:
    path: ../material_neumorphic_text

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
