name: cicd

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.5"
          channel: "stable"
          cache: true
      - uses: bluefireteam/melos-action@main
      - run: melos run format-check

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.5"
          channel: "stable"
      - uses: bluefireteam/melos-action@main
      - name: "Analyze"
        uses: invertase/github-action-dart-analyzer@v2.0.0
